In [2]:
import numpy as np


In [3]:
data = np.random.randn(30)

In [4]:
data

array([-1.31102287,  0.83474405, -1.23531423, -0.42615468, -0.34450977,
        0.10964486, -0.00941557, -0.41795992,  0.5161598 , -0.07408332,
        0.01133458, -1.09527986,  1.37311993, -0.96234661,  1.10490566,
        0.78726003,  0.48698455, -0.41138156,  1.19313358,  0.53846418,
       -1.2279935 , -0.80510392,  0.29641143, -0.79709414, -0.11458928,
       -1.56996039,  1.05926701,  0.06460107, -0.64020533, -0.96273308])

In [5]:
sample = np.random.choice(data,15)

In [6]:
sample

array([-1.09527986, -1.09527986,  0.83474405, -0.11458928,  0.06460107,
        0.48698455,  1.37311993, -1.09527986,  1.05926701,  0.5161598 ,
        1.19313358,  0.53846418, -0.41795992, -0.79709414, -1.09527986])

In [7]:
num_std = np.std(data)

In [8]:
num_std

0.8155062410022401

In [10]:
sample_std = np.std(sample)

In [11]:
sample_

array([-1.09527986, -1.09527986,  0.83474405, -0.11458928,  0.06460107,
        0.48698455,  1.37311993, -1.09527986,  1.05926701,  0.5161598 ,
        1.19313358,  0.53846418, -0.41795992, -0.79709414, -1.09527986])