In [88]:
import numpy as np
import pandas as pd
import seaborn as sns

In [90]:
df = pd.read_csv('spam.csv')

In [92]:
df

text  spam
0    subject:Beatae est possimus esse tempore sapie...     1
1    subject:There are three primany school in our ...     1
2    subject:how are you bangladesh.  I am fine and...     1
3    subject:Beatae est possimus esse tempore sapie...     1
4    subject:There are three primany school in our ...     1
..                                                 ...   ...
494  subject: No body belive layer. I am all ready ...     0
495  subject: No body belive layer. I am all ready ...     0
496  subject: muna is a very beautifull girls in ou...     0
497  subject:I love datascience.I am study Machine ...     0
498  subject: No body belive layer. I am all ready ...     0

[499 rows x 2 columns]

In [94]:
df['spam'].value_counts()

0    302
1    197
Name: spam, dtype: int64

In [96]:
df.drop_duplicates(inplace=True)

In [98]:
df

text  spam
0    subject:Beatae est possimus esse tempore sapie...     1
1    subject:There are three primany school in our ...     1
2    subject:how are you bangladesh.  I am fine and...     1
197  subject:I love datascience.I am study Machine ...     0
198  subject: No body belive layer. I am all ready ...     0
199  subject: muna is a very beautifull girls in ou...     0

In [99]:
df['spam'].value_counts()

1    3
0    3
Name: spam, dtype: int64

In [102]:
df.isnull().sum()

text    0
spam    0
dtype: int64

# saparate test

In [103]:
x = df.text.values

In [104]:
x

array(['subject:Beatae est possimus esse tempore sapiente consectetur ratione',
       'subject:There are three primany school in our village.',
       'subject:how are you bangladesh.  I am fine and you.I am very well.',
       'subject:I love datascience.I am study Machine learning',
       'subject: No body belive layer. I am all ready suceessful life.',
       'subject: muna is a very beautifull girls in our collage. How are you.'],
      dtype=object)

In [105]:
y = df.spam.values

In [106]:
y

array([1, 1, 1, 0, 0, 0], dtype=int64)

In [107]:
from sklearn.model_selection import train_test_split

In [109]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2)

In [110]:
xtest

array(['subject:Beatae est possimus esse tempore sapiente consectetur ratione',
       'subject: muna is a very beautifull girls in our collage. How are you.'],
      dtype=object)

In [112]:
ytest

array([1, 0], dtype=int64)

In [113]:
from sklearn.feature_extraction.text import CountVectorizer

In [115]:
cv = CountVectorizer()

In [116]:
x_train = cv.fit_transform(xtrain)

In [117]:
x_train.toarray()

array([[1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
        1, 0, 1, 1, 0, 1, 0, 0],
       [0, 2, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 1, 2]], dtype=int64)

In [119]:
from sklearn.naive_bayes import MultinomialNB

In [120]:
model = MultinomialNB()

In [126]:
model.fit(x_train ,ytrain)

MultinomialNB()

In [127]:
x_test = cv.fit_transform(xtest)

In [129]:
x_test.toarray()

array([[0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1]],
      dtype=int64)

In [131]:
model.score(x_test,ytest)

ValueError: dimension mismatch